"""Generated by `wake-sol gen`. Importing this package registers
every program below into wake_sol._interface.REGISTRY (import
side effect)."""
from . import futarchy as futarchy  # noqa: F401

__all__ = ["futarchy"]
__generated_by__ = "wake-sol gen 0.2.0"
