[package]
name = "autocrat"
version = "0.5.0"
description = "SVM-based program for running futarchy"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "autocrat"

[features]
default = ["custom-heap"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
custom-heap = []

[dependencies]
anchor-lang = "^0.29.0"
anchor-spl = "^0.29.0"
solana-security-txt = "1.1.1"
conditional_vault = { path = "../conditional_vault", features = ["cpi"] }
squads-multisig-program = { git = "https://github.com/Squads-Protocol/v4", package = "squads-multisig-program", rev = "6d5235da621a2e9b7379ea358e48760e981053be", features = ["cpi"] }
