[package]
name = "autocrat"
version = "0.5.0"
description = "SVM-based program for running futarchy"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "autocrat"

[features]
default = ["custom-heap"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
custom-heap = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "^0.31.1"
anchor-spl = "^0.31.1"
solana-security-txt = "1.1.1"
conditional_vault = { path = "../conditional_vault", features = ["cpi"] }
fixed = "^1.26.0"
