[package]
name = "launchpad"
version = "0.6.1"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "launchpad"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["custom-heap"]
devnet = []
production = []
custom-heap = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
futarchy = { path = "../futarchy", features = ["cpi"] }
price_based_performance_package = { path = "../price_based_performance_package", features = ["cpi"] }
spl-memo = "=4.0.0"
solana-program = "=1.17.14"
spl-token = "=4.0.0"
ahash = "=0.8.6"
solana-security-txt = "1.1.1"
squads-multisig-program = { git = "https://github.com/Squads-Protocol/v4", package = "squads-multisig-program", rev = "6d5235da621a2e9b7379ea358e48760e981053be", features = ["cpi"] }
damm_v2_cpi = { path = "../damm_v2_cpi", features = ["cpi"] }
