[package]
name = "redeem"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "redeem"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
devnet = ["raydium-cpmm-cpi/devnet"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed", "event-cpi"] }
anchor-spl = "0.29.0"
raydium-cpmm-cpi = { git = "https://github.com/raydium-io/raydium-cpi", package = "raydium-cpmm-cpi", branch = "anchor-0.29.0" }
autocrat = { git = "https://github.com/metaDAOproject/futarchy.git", branch = "v4-stable", features = ["cpi"] }
launchpad = { git = "https://github.com/metaDAOproject/futarchy.git", branch = "v4-stable", features = ["cpi"] }
solana-security-txt = "1.1.1"
solana-program = "=1.17.14"
spl-token = "4.0.0"
