[package]
name = "shared_liquidity_manager"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "shared_liquidity_manager"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
autocrat = { path = "../autocrat", features = ["cpi"] }
raydium-cpmm-cpi = { git = "https://github.com/raydium-io/raydium-cpi", package = "raydium-cpmm-cpi", branch = "anchor-0.29.0" }
spl-memo = "=4.0.0"
solana-program = "=1.17.14"
spl-token = "=4.0.0"
ahash = "=0.8.6"
solana-security-txt = "1.1.1"
anchor-spl = "^0.29.0"


