name: anchor-test
on:
  push:
    branches:
      - develop
      - production
  pull_request:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  run-anchor-test:
    runs-on:
      group: speed

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'yarn'
          cache-dependency-path: sdk/yarn.lock

      - name: Install SDK dependencies
        run: |
          cd sdk
          yarn install

      - name: Build SDK
        run: |
          cd sdk
          yarn build

      - uses: metadaoproject/anchor-test@v2.3
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.31'
          node-version: '20.18.0'

