name: anchor-test
on:
  push:
    branches:
      - develop
      - production
  pull_request:
  workflow_dispatch:

jobs:
  run-anchor-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: metadaoproject/anchor-test@v2.6.1
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.16'