name: anchor-test
on:
  push:
    branches:
      - develop
      - production
  pull_request:

jobs:
  run-anchor-test:
    runs-on: ubuntu-22.04

    env:
      RUSTUP_TOOLCHAIN: '1.86.0'

    steps:
      - uses: actions/checkout@v4

      - uses: metadaoproject/anchor-test@v2.5
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.17.16'