name: Deploy Programs to Mainnet with IDL and Verified builds

on:
  workflow_dispatch:
    inputs:
      program:
        description: "Program to deploy"
        required: true
        type: choice
        options:
          - conditional_vault_v4
          - futarchy_v6
          - launchpad_v6
          - price_based_performance_package_v6
          - launchpad_v7
          - launchpad_v8
          - bid_wall
          - liquidation
          - mint_governor
          - performance_package_v2
      priority-fee:
        description: "Priority fee in microlamports"
        required: true
        default: "300000"
        type: string

permissions:
  contents: read

jobs:
  conditional-vault-v4:
    if: inputs.program == 'conditional_vault_v4'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "conditional_vault"
      override-program-id: "VLTX1ishMBbcX3rdBWGssxawAo1Q2X2qxYFYqiGodVg"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  liquidation:
    if: inputs.program == 'liquidation'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "liquidation"
      override-program-id: "LiQnowFbFQdYyZhF4pUbpsrZCjxRTQ1upKJxZ2VXjde"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  futarchy-v6:
    if: inputs.program == 'futarchy_v6'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "futarchy"
      override-program-id: "FUTARELBfJfQ8RDGhg1wdhddq1odMAJUePHFuBYfUxKq"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  launchpad-v6:
    if: inputs.program == 'launchpad_v6'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "launchpad"
      override-program-id: "MooNyh4CBUYEKyXVnjGYQ8mEiJDpGvJMdvrZx1iGeHV"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  price-based-performance-package-v6:
    if: inputs.program == 'price_based_performance_package_v6'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "price_based_performance_package"
      override-program-id: "pbPPQH7jyKoSLu8QYs3rSY3YkDRXEBojKbTgnUg7NDS"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}
  
  launchpad-v7:
    if: inputs.program == 'launchpad_v7'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "launchpad_v7"
      override-program-id: "moontUzsdepotRGe5xsfip7vLPTJnVuafqdUWexVnPM"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  bid-wall:
    if: inputs.program == 'bid_wall'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "bid_wall"
      override-program-id: "WALL8ucBuUyL46QYxwYJjidaFYhdvxUFrgvBxPshERx"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  mint-governor:
    if: inputs.program == 'mint_governor'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "mint_governor"
      override-program-id: "gvnr27cVeyW3AVf3acL7VCJ5WjGAphytnsgcK1feHyH"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  performance-package-v2:
    if: inputs.program == 'performance_package_v2'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "performance_package_v2"
      override-program-id: "pPV2pfrxnmstSb9j7kEeCLny5BGj6SNwCWGd6xbGGzz"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}

  launchpad-v8:
    if: inputs.program == 'launchpad_v8'
    uses: ./.github/workflows/reusable-build.yaml
    with:
      program: "launchpad_v8"
      override-program-id: "moonDJUoHteKkGATejA5bdJVwJ6V6Dg74gyqyJTx73n"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      features: "production"
      priority-fee: ${{ inputs.priority-fee }}
    secrets:
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}